import { Ability } from "./ability";
import { AbilityScore } from "./abilityscore";
import { Condition } from "./condition";
import { Defense } from "./defense";
import { Feat } from "./feat";
import { Influence } from "./influence";
import { Modifier } from "./modifier";
import { Proficiency } from "./proficiency";
import { Race } from "./race";
import { Sense } from "./sense";
import { Speed } from "./speed";
import { Spell } from "./spell";

export class Character {
    id: string;
    userId: string;
    name: string;
    level: number;
    picture: string;
    inspiration: boolean;
    initiative: number;
    proficiency_Bonus: number;
    armor_Class: number;
    exhaustion_Level: number;
    current_Carrying_Weight: number;
    max_Carrying_Weight: number;
    encumbered: boolean;
    current_Hit_Points: number;
    current_Max_Hit_Points: number;
    base_Max_Hit_Points: number;
    max_Hit_Points_Modifier: number;
    temp_Hit_Points: number;
    xp: number;
    alignment: string;
    gender: string;
    eye_Color: string;
    height: number;
    size: string;
    faith: string;
    hair_Color: string;
    skin_Color: string;
    age: number;
    weight: number;
    appearance: string;
    backstory: string;
    notes: string;
    death_Saving_Throw_Success: number;
    death_Saving_Throw_Failure: number;
    race: string;

    races: Race[];
    abilityScores: AbilityScore[];
    feats: Feat[];
    abilities: Ability[];
    modifiers: Modifier[];
    abilitySpells: Spell[];
    defenses: Defense[];
    senses: Sense[];
    speeds: Speed[];
    conditions: Condition[];
    influences: Influence[];
    proficiencies: Proficiency[];
}