export enum EquipmentType {
    "Adventuring Gear",
    "Tool",
    "Instrument",
    "Simple Melee Weapon",
    "Martial Melee Weapon",
    "Gemstone",
    "Coin",
    "Holy Symbol",
    "Arcane Focus",
    "Druidic Focus",
    "Simple Ranged Weapon",
    "Martial Ranged Weapon",
    "Firearm Ranged Weapon",
    "Ammunition",
    "Mount",
    "Vehicle (Land)",
    "Vehicle (Water)",
    "Poison",
    "Potion",
    "Light Armor",
    "Medium Armor",
    "Heavy Armor",
    "Equipment Pack",
    "Magic Item"
}
