export enum SpellRange {
    SELF = "Self",
    TOUCH = "Touch",
    FIVE_FT = "5 ft",
    TEN_FT = "10 ft",
    TWENTY_FT = "20 ft",
    THIRTY_FT = "30 ft",
    SIXTY_FT = "60 ft",
    NINETY_FT = "90 ft",
    HUNDRED_FT = "100 ft",
    HUNDREDTWENTY_FT = "120 ft",
    HUNDREDFIFTY_FT = "150 ft",
    THREEHUNDRED_FT = "300 ft",
    FIVEHUNDRED_FT = "500 ft",
    THOUSAND_FT = "1000 ft",
    ONE_MILE = "1 mile",
    FIVEHUNDRED_MILES = "500 miles",
    SIGHT = "Sight",
    UNLIMITED = "Unlimited"
}
